import md_to_code

def test_readme():
    md_to_code.convert_to('test', 'README.md', 'tests/autogenerated_readme.py')
    import autogenerated_readme
    autogenerated_readme.run_test()

def test_soec_example():
    md_to_code.convert_to('test', 'docs/source/examples/soec_methane.md', 'tests/autogenerated_soec_example.py')
    import autogenerated_soec_example
    autogenerated_soec_example.run_test()