name: Build and Deploy Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Install gaspype and dependencies
        run: |
          echo "Create a dummy file to ensure gaspype does't crash"
          mkdir -p src/gaspype/data
          printf 'gapy\x00\x00\x00\x00' > src/gaspype/data/therm_data.bin
          pip install .[doc_build]
          python -m ipykernel install --user --name temp_kernel --display-name "Python (temp_kernel)"
      - name: Generate Docs
        run: python ./docs/source/generate_class_list.py
      - name: Generate Examples
        run: python ./docs/source/render_examples.py
      - name: Build Docs
        run: |
          cp LICENSE docs/source/LICENSE.md
          cd docs
          sphinx-apidoc -o ./source/ ../src/ -M --no-toc
          rm ./source/*.rst
          make html
          touch ./build/html/.nojekyll
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/build/html
